=== mekcone/mekcone-studio/resources/xsd/excrud.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="project">
        <xs:complexType>
            <xs:all>
                <xs:element name="groupId" type="xs:string"></xs:element>
                <xs:element name="artifactId" type="xs:string"></xs:element>
                <xs:element name="version" type="xs:string"></xs:element>
                <xs:element name="name" type="xs:string"></xs:element>
                <xs:element name="description" type="xs:string"></xs:element>
                <xs:element ref="apiDocument"></xs:element>
                <xs:element ref="databases"></xs:element>
                <xs:element ref="exports"></xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="apiDocument">
        <xs:complexType>
            <xs:all>
                <xs:element name="title" type="xs:string"></xs:element>
                <xs:element name="description" type="xs:string"></xs:element>
                <xs:element name="keywords">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="keyword" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="type" use="required" type="xs:string" />
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="databases">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="database">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tables">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="table" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="columns" maxOccurs="1">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="column" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
                                                                        <xs:attribute name="type" type="xs:string" use="required"></xs:attribute>
                                                                        <xs:attribute name="filter" type="xs:boolean" use="optional" default="false"></xs:attribute>
                                                                        <xs:attribute name="primaryKey" type="xs:boolean" use="optional"></xs:attribute>
                                                                        <xs:attribute name="description" type="xs:string" use="optional"></xs:attribute>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
                                                <xs:attribute name="description" type="xs:string"></xs:attribute>
                                                <xs:attribute name="primaryKey" type="xs:string"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="type" type="xs:string" use="optional" default="mysql"></xs:attribute>
                        <xs:attribute name="host" type="xs:string" use="required"></xs:attribute>
                        <xs:attribute name="username" type="xs:string" use="required"></xs:attribute>
                        <xs:attribute name="password" type="xs:string" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="exports">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="export" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="properties" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="application_name" minOccurs="0" maxOccurs="1" type="xs:string"/>
                                        <xs:element name="cross_origin_enable" minOccurs="0" maxOccurs="1" default="false" type="xs:boolean"/>
                                        <xs:element name="cross_origin_allowed_origins" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
                                        <xs:element name="lombok_enable" minOccurs="0" maxOccurs="1" default="true" type="xs:boolean"/>
                                        <xs:element name="mybatis_enable" minOccurs="0" maxOccurs="1" default="true" type="xs:boolean"/>
                                        <xs:element name="page_helper_enable" minOccurs="0" maxOccurs="1" default="true" type="xs:boolean"/>
                                        <xs:element name="server_port" minOccurs="0" maxOccurs="1" default="8080" type="xs:integer"/>
                                        <xs:element name="swagger2_enable" minOccurs="0" maxOccurs="1" default="true" type="xs:boolean"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:all>
                        <xs:attribute name="type" use="required"></xs:attribute>
                        <xs:attribute name="enable" use="optional" type="xs:boolean" default="true"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== mekcone/mekcone-studio/example/mall/excrud.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xsi:noNamespaceSchemaLocation="file:///D:/Projects/excrud/resources/xsd/excrud.xsd">
    <groupId>com.mekcone.excrud.example</groupId>
    <artifactId>mall</artifactId>
    <name>MekCone 商城</name>
    <version>0.0.1</version>
    <description>MekCone Mall Project</description>

    <apiDocument>
        <title>MekCone 商城{br}API 文档</title>
        <!-- <description>MekCone 商城接口文档</description> -->
        <keywords>
            <keyword type="create">创建</keyword>
            <keyword type="retrieve">获取</keyword>
            <keyword type="retrieveList">获取所有</keyword>
            <keyword type="update">更新</keyword>
            <keyword type="delete">删除</keyword>
        </keywords>
    </apiDocument>

    <databases>
        <database type="mysql" host="localhost:3306" username="root" password="123456">
            <tables>
                <table name="goods" description="商品对象">
                    <columns>
                        <column name="goods_id" type="int" primaryKey="true" description="商品ID"/>
                        <column name="goods_name" type="varchar(50)" description="商品名称"/>
                        <column name="catalogue_id" type="varchar(50)" description="商品类别ID"/>
                        <column name="goods_price" type="double" description="商品价格"/>
                        <column name="goods_description" type="varchar(50)" description="商品描述"/>
                    </columns>
                </table>
                <table name="cart" description="购物车对象">
                    <columns>
                        <column name="item_id" type="varchar(50)" primaryKey="true" description="购物车条目ID"/>
                        <column name="goods_id" type="varchar(50)" description="商品ID"/>
                        <column name="user_id" type="varchar(20)" description="用户ID"/>
                        <column name="amount" type="int" description="购物车选购数目"/>
                    </columns>
                </table>
                <table name="catalogue" description="商品门类">
                    <columns>
                        <column name="catalogue_id" type="varchar(50)" primaryKey="true" description="商品类别ID"/>
                        <column name="catalogue_name" type="varchar(50)" description="商品类别名"/>
                    </columns>
                </table>
            </tables>
        </database>
    </databases>

    <exports>
        <export type="spring-boot-backend" enable="false">
            <properties>
                <application_name>Mall</application_name>
                <cross_origin_enable>false</cross_origin_enable>
                <cross_origin_allowed_origins>*</cross_origin_allowed_origins>
                <lombok_enable>true</lombok_enable>
                <mybatis_enable>true</mybatis_enable>
                <page_helper_enable>true</page_helper_enable>
                <server_port>9090</server_port>
                <swagger2_enable>true</swagger2_enable>
            </properties>
        </export>
        <export type="enterprise-official-website" enable="true">
            <properties>
                <title>MekCone China</title>

            </properties>
        </export>
    </exports>
</project>

=== mekcone/mekcone-studio/examples/blog/excrud.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xsi:noNamespaceSchemaLocation="../../resources/xsd/excrud.xsd">
    <groupId>com.mekcone.excrud.example</groupId>
    <artifactId>blog</artifactId>
    <name>MekCone 博客</name>
    <version>0.0.1</version>
    <description>MekCone Blog Project</description>
    <language>zh-CN</language>

    <apiDocument>
        <title>MekCone 博客 {br}API 文档</title>
        <!-- <description>MekCone 商城接口文档</description> -->
        <keywords>
            <keyword type="create">创建</keyword>
            <keyword type="retrieve">获取</keyword>
            <keyword type="retrieveList">获取所有</keyword>
            <keyword type="update">更新</keyword>
            <keyword type="delete">删除</keyword>
        </keywords>
    </apiDocument>

    <databases>
        <database type="mysql" host="localhost:3306" name="mekcone_blog" username="root" password="123456">
            <tables>
                <table name="article" description="文章对象">
                    <columns>
                        <column name="article_id" type="int" primaryKey="true"/>
                        <column name="article_title" type="varchar(50)"/>
                        <column name="article_author" type="varchar(50)"/>
                        <column name="article_content" type="double" detail="true"/>
                        <column name="publish_time" type="varchar(50)" detail="true"/>
                    </columns>
                </table>
                <table name="catalogue" description="文章门类">
                    <columns>
                        <column name="catalogue_id" type="varchar(50)" primaryKey="true"/>
                        <column name="catalogue_name" type="varchar(50)"/>
                    </columns>
                </table>
            </tables>
        </database>
    </databases>

    <exports>
        <export type="spring-boot-backend" enable="true">
            <properties>
                <application_name>Blog</application_name>
                <cross_origin_allowed_methods>GET, POST, PUT, DELETE</cross_origin_allowed_methods>
                <cross_origin_allowed_origins>*</cross_origin_allowed_origins>
                <lombok_enable>true</lombok_enable>
                <mybatis_enable>true</mybatis_enable>
                <page_helper_enable>true</page_helper_enable>
                <server_port>10011</server_port>
                <swagger2_enable>true</swagger2_enable>
            </properties>
        </export>
    </exports>
</project>
